apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: camunda
  namespace: camunda
spec:
  repo: https://helm.camunda.io
  chart: camunda-platform
  version: 12.6.1
  targetNamespace: camunda
  valuesContent: |-
    global:
      identity:
        auth: 
          publicIssuerUrl: "https://camunda.local/auth/realms/camunda-platform"
          operate:
            redirectUrl: "https://camunda.local/operate"
      ingress:
        enabled: true
        host: "camunda.local"
        className: "traefik"
      image:
        tag: "8.7.0"
    
    identity:
      contextPath: "/identity"
      image:
        tag: "8.7.0"
      env:
      - name: KEYCLOAK_CLIENTS_2_ID
        value: e2e
      - name: KEYCLOAK_CLIENTS_2_NAME
        value: E2E User
      - name: KEYCLOAK_CLIENTS_2_SECRET
        value: e2e-client-secret
      - name: KEYCLOAK_CLIENTS_2_REDIRECT_URIS_0
        value: /operate/identity-callback
      - name: KEYCLOAK_CLIENTS_2_ROOT_URL
        value: https://v87-newtest.camunda.local
      - name: KEYCLOAK_CLIENTS_2_TYPE
        value: CONFIDENTIAL
      - name: KEYCLOAK_CLIENTS_2_PERMISSIONS_0_RESOURCE_SERVER_ID
        value: operate-api
      - name: KEYCLOAK_CLIENTS_2_PERMISSIONS_0_DEFINITION
        value: "read:*"
      - name: KEYCLOAK_CLIENTS_2_PERMISSIONS_1_RESOURCE_SERVER_ID
        value: operate-api
      - name: KEYCLOAK_CLIENTS_2_PERMISSIONS_1_DEFINITION
        value: "write:*"    
    
    identityKeycloak:
      livenessProbe:
        enabled: false
      readinessProbe:
        enabled: false
      resources:
        requests:
          cpu: 1m
          memory: 1m
        limits:
          memory: 2G
    
    optimize:
      enabled: false

    zeebe:
      clusterSize: 1
      partitionCount: 1
      replicationFactor: 1
      pvcSize: 1Gi
      image:
        tag: "8.7.0"
      resources:
        requests:
          cpu: 1m
          memory: 1m
    
    zeebeGateway:
      contextPath: "/zeebe/"
      replicas: 1
      service:
        annotations:
          traefik.ingress.kubernetes.io/service.serversscheme: h2c
        type: LoadBalancer
      ingress:
        enabled: true
        host: "zeebe.camunda.local"
        className: "traefik"
      image:
        tag: "8.7.0"
      resources:
        requests:
          cpu: 1m
          memory: 1m
        limits: 
          memory: 1G
    
    connectors:
      enabled: false
      inbound:
        mode: disabled
        
    elasticsearch:
      extraConfig:
        "cluster.routing.allocation.disk.threshold_enabled": false
      master:
        replicaCount: 1
        # Request smaller persistent volumes.
        persistence:
          size: 1Gi
        resources:
          requests:
            cpu: 1m
            memory: 1m
          
    operate:
      contextPath: "/operate"
      migration:
        enabled: false
      image:
        tag: "8.7.0"
      requests:
        cpu: 1m
        memory: 1m
        
    tasklist:
      enabled: false
      contextPath: "/tasklist"
    