camunda.client.auth.client-id=orchestration
camunda.client.auth.client-secret=token
camunda.client.rest-address=http://localhost:8080/core
camunda.client.grpc-address=http://zeebe.camunda.local/core
#camunda.client.identity.base-url=http://camunda.local/auth/
camunda.client.auth.token-url=http://camunda.local/auth/realms/camunda-platform/protocol/openid-connect/token
#camunda.rpa.zeebe.auth-endpoint=http://camunda.local/auth/realms/camunda-platform/protocol/openid-connect
camunda.rpa.e2e.operate-url=http://camunda.local/core/v2
camunda.rpa.e2e.client-id=orchestration
camunda.rpa.e2e.client-secret=token
camunda.rpa.e2e.operate-client=${camunda.client.auth.client-id}
camunda.rpa.e2e.operate-client-secret=${camunda.client.auth.client-secret}
