name: Build

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: "ghcr.io/camunda/rpa-worker-base-image:202501281531"
    permissions:
      contents: read
      packages: write
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build
        run: |
          ./gradlew setVersion
          ./gradlew -console plain --build-cache build
          
      - name: Generate Release Header
        run: ./gradlew generateReleaseHeader
        if: github.ref_type == 'tag'
          
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        if: github.ref_type == 'tag'
        with:
          name: executable-application-jar
          path: build/libs/*.jar
          retention-days: 1
          
      - name: Upload Release Header
        uses: actions/upload-artifact@v4
        if: github.ref_type == 'tag'
        with:
          name: release-header
          path: build/releasenotes_header.md
          retention-days: 1
      
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            build/test-results/**/*.xml
            
  release:
    needs: build
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artefacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            *.jar
          prerelease: ${{ contains(github.ref_name, '-') }}
          preserve_order: true
          generate_release_notes: true
          body_path: releasenotes_header.md
    